Add sys-init script (PPL-83).

diff --git a/scripts/start b/scripts/start
--- a/scripts/start
+++ b/scripts/start
@@ -1,30 +1,79 @@
 #!/usr/bin/env bash
+
 BASEDIR=$(cd "$(dirname "$0")"; pwd)
 LISTEN="${LISTEN:-":LISTEN"}"
 HOST="${LISTEN%:*}"
 PORT="${LISTEN#*:}"
 BG="${BG:-"yes"}"
+QUIET="${QUIET:-"no"}"
 
-app_is_running() {
-   pid=$(ps ax | grep "percona-qan-app-$PORT" | grep -v grep | awk '{print $1}')
-   [ "$pid" ] && return 0 # running
-   return 1 # not running
+SERVICE="percona-qan-app"
+LOGFILE="$BASEDIR/$SERVICE.log"
+PIDFILE="$BASEDIR/$SERVICE.pid"
+PID=""
+FIXPIDFILE="yes"
+
+app_pid() {
+   PID=$(ps ax | grep "$SERVICE-$PORT" | grep -v grep | awk '{print $1}')
 }
 
-if app_is_running; then
-   kill $pid
-fi
-
-cmd="python -c \"import BaseHTTPServer as bhs, SimpleHTTPServer as shs; bhs.HTTPServer(('$HOST', $PORT), shs.SimpleHTTPRequestHandler).serve_forever() # percona-qan-app-$PORT\""
-if [ "$BG" = "yes" ]; then
-   eval "$cmd >> percona-qan-app.log 2>&1 &"
-   pid=$!
-   if [ $? -ne 0 ]; then
-      echo "Error started Percona QAN app. Check the log file: $BASEDIR/percona-qan-app.log" >&2
-      exit 1
+app_is_running() {
+   app_pid
+   if [ -f "$PIDFILE" ]; then
+      if [ "$PID" ]; then
+         PID_IN_FILE="$(cat $PIDFILE)"
+         if [ "$PID" -eq "$PID_IN_FILE" ]; then
+            return 0 # running and PID file correct
+         else
+            if [ "$FIXPIDFILE" = "yes" ]; then
+               echo "PID in $PIDFILE is incorrect, fixing"
+               echo $PID > $PIDFILE
+            fi
+            return 0 # running but had to correct PID file
+         fi
+      else
+         echo "$SERVICE-$PORT is not running, removing stale PID file $PIDFILE" >&2
+         rm -f "$PIDFILE"
+         return 1 # not running
+      fi
+   else
+      if [ "$PID" ]; then
+         if [ "$FIXPIDFILE" = "yes" ]; then
+            echo "$SERVICE-$PORT is running (PID $PID) but $PIDFILE is missing, fixing" >&2
+            echo $PID > "$PIDFILE"
+         fi
+         return 0 # running
+      else
+         return 1 # not running, no PID or PID file
+      fi
    fi
-   echo "Percona Query Analytics app running as PID $pid"
-else
-   echo "Percona Query Analytics app listening on $LISTEN..."
-   eval "$cmd"
+   echo "Cannot determine if $SERVICE-$PORT is running" >&2 # this shouldn't happen
+   return 1 # not running?
+}
+
+start_app() {
+   cmd="python -c \"import BaseHTTPServer as bhs, SimpleHTTPServer as shs; bhs.HTTPServer(('$HOST', $PORT), shs.SimpleHTTPRequestHandler).serve_forever() # $SERVICE-$PORT\""
+   if [ "$BG" = "yes" ]; then
+      eval "$cmd >> $LOGFILE 2>&1 &"
+      PID=$!
+      if [ $? -ne 0 ]; then
+         echo "Error started Percona QAN app. Check the log file: $BASEDIR/$SERVICE.log" >&2
+         exit 1
+      fi
+      echo $PID > "$PIDFILE"
+      [ "$QUIET" = "no" ] && echo "Percona Query Analytics app listening on $LISTEN (PID $PID)"
+   else
+      echo "Percona Query Analytics app listening on $LISTEN..."
+      eval "$cmd"
+   fi
+}
+
+# This super fancy line is true if this script is called from the command line,
+# else it's false and it's probably being sourced by an init script.
+if [ "${0##*/}" = "start" ] || [ "${0##*/}" = "bash" -a "${_:-""}" = "$0" ]; then
+   if app_is_running; then
+      echo "Percona Query Analytics app is already running (PID $PID)"
+   else
+      start_app
+   fi
 fi
